### PR TITLE
Smaller Docker image, CircleCI, TravisCI, Docker Hub

### PR DESCRIPTION
**Pull request by smiller171**
You need to set DOCKER_USER, DOCKER_EMAIL, and DOCKER_PASS in CircleCI to push the image to Docker hub.

### CODE REVIEW

**Comment by hverr** [comment]
Any reason why you strip the final binary?

**Comment by smiller171** [comment]
@hverr That's me getting obsessive about making the image as tiny as possible without fully understanding what I'm doing. Any impact of this I should be aware of?

**Comment by hverr** [comment]
In this case its probably fine. I think previous Go versions had problems with stripped binaries and it's not officially supported, but don't ask me to back this up with references.

---

Anyways I'm willing to take a 2MB binary increase to eliminate  the 0.001% chance of an inexplicable error due to stripping. I should probably let you know that I've changed the master branch to disable stripping.

**Comment by smiller171** [comment]
Sure thing. There's a bunch of stuff in my master branch in the readme for adding additional status badges and such that I pulled out of this PR because they reference my resources, but you are welcome to copy them for your own use. I also have a notifications section in my circle.yml that sends notifications to OpsGenie and Gitter when the build fails if you care to implement the same.

**Pull request merged**
